"""add created_at and shelved_at to products

Revision ID: 313040ac50e4
Revises: eb30bbac77fc
Create Date: 2026-09-01 15:29:21.986869

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '313040ac50e4'
down_revision: str | Sequence[str] | None = 'eb30bbac77fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('shelved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'shelved_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
