"""add is_active to products

Revision ID: eb30bbac77fc
Revises: ab8ed1f63d78
Create Date: 2026-09-01 14:38:51.134613

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb30bbac77fc'
down_revision: str | Sequence[str] | None = 'ab8ed1f63d78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 给已有数据的表加 NOT NULL 列：先带 server_default 补值，再加约束
    op.add_column(
        'products', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False)
    )
    # 存量行已补 true，去掉数据库默认（上架状态由应用代码管理）
    op.alter_column('products', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
